
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Nov 18 2025 14:36:02 IST (Nov 18 2025 09:06:02 UTC)

// Verification Directory fv/counter 

module counter(clk, start, done, Tclk, scan_enable, TDI, TDO);
  input clk, start, Tclk, scan_enable, TDI;
  output done, TDO;
  wire clk, start, Tclk, scan_enable, TDI;
  wire done, TDO;
  wire [7:0] cnt;
  wire n_0, n_1, n_2, n_3, n_4, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_28, n_30;
  SDFF_X2 done_reg(.CK (clk), .D (n_22), .SI (n_4), .SE (scan_enable),
       .Q (done), .QN (TDO));
  SDFF_X2 \cnt_reg[4] (.CK (clk), .D (n_21), .SI (n_3), .SE
       (scan_enable), .Q (cnt[4]), .QN (n_4));
  AND4_X2 g523__2398(.A1 (n_20), .A2 (n_17), .A3 (n_28), .A4 (start),
       .ZN (n_22));
  SDFF_X2 \cnt_reg[3] (.CK (clk), .D (n_18), .SI (n_2), .SE
       (scan_enable), .Q (cnt[3]), .QN (n_3));
  NOR2_X2 g527__5107(.A1 (n_19), .A2 (n_7), .ZN (n_21));
  AND3_X2 g525__6260(.A1 (n_19), .A2 (n_11), .A3 (n_14), .ZN (n_20));
  SDFF_X2 \cnt_reg[2] (.CK (clk), .D (n_15), .SI (n_1), .SE
       (scan_enable), .Q (cnt[2]), .QN (n_2));
  INV_X2 g529(.A (n_17), .ZN (n_18));
  XOR2_X2 g531__4319(.A (n_16), .B (cnt[4]), .Z (n_19));
  OAI211_X2 g530__8428(.A (start), .B (n_16), .C1 (cnt[3]), .C2 (n_13),
       .ZN (n_17));
  SDFF_X2 \cnt_reg[1] (.CK (clk), .D (n_12), .SI (n_0), .SE
       (scan_enable), .Q (cnt[1]), .QN (n_1));
  INV_X2 g533(.A (n_14), .ZN (n_15));
  OAI211_X2 g534__5526(.A (start), .B (n_10), .C1 (cnt[2]), .C2 (n_9),
       .ZN (n_14));
  NAND2_X2 g535__6783(.A1 (cnt[3]), .A2 (n_13), .ZN (n_16));
  SDFF_X2 \cnt_reg[0] (.CK (clk), .D (n_8), .SI (TDI), .SE
       (scan_enable), .Q (cnt[0]), .QN (n_0));
  INV_X2 g536(.A (n_11), .ZN (n_12));
  INV_X2 g539(.A (n_10), .ZN (n_13));
  OAI211_X2 g537__3680(.A (start), .B (n_6), .C1 (cnt[1]), .C2 (n_28),
       .ZN (n_11));
  NAND2_X2 g540__1617(.A1 (cnt[2]), .A2 (n_9), .ZN (n_10));
  NOR2_X2 g541__2802(.A1 (n_28), .A2 (n_7), .ZN (n_8));
  INV_X2 g542(.A (n_6), .ZN (n_9));
  NAND2_X2 g543__1705(.A1 (cnt[1]), .A2 (n_28), .ZN (n_6));
  INV_X2 g544(.A (start), .ZN (n_7));
  INV_X4 drc_bufs(.A (n_30), .ZN (n_28));
  INV_X2 drc_bufs554(.A (cnt[0]), .ZN (n_30));
endmodule

